# This is a basic workflow to help you get started with Actions

name: Backend

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      # instalação do nodejs
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2
        with:
          node_version: 12.x
      
      - name: Install dependencies
        run: npm install
      
      - name: Run build
        run: npm run build
      
      - name: Copy to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          source: "."
          target: "test"
